name: CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Bundler & 依存関係インストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: RuboCop lint チェック
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: yaseru_meshi_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/yaseru_meshi_test
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Bundler & 依存関係インストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: DB作成・マイグレーション
        run: bundle exec rails db:create db:migrate

      - name: RSpec テスト実行
        run: bundle exec rspec

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SSH鍵をセットアップ
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.HEROKU_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts

      - name: Remove existing heroku remote if exists
        run: git remote remove heroku || true

      - name: Add heroku git remote (SSH形式)
        run: git remote add heroku git@heroku.com:${{ secrets.HEROKU_APP_NAME }}.git

      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Bundler & 依存関係インストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: git remote 確認 (デバッグ用)
        run: git remote -v

      - name: Herokuにpush（デプロイ）
        run: git push heroku main:refs/heads/main --force
