name: CI and Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3
      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Bundler & 依存関係インストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: RuboCop lint チェック
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: yaseru_meshi_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/yaseru_meshi_test
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3
      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Bundler & 依存関係インストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: DB作成・マイグレーション
        run: bundle exec rails db:create db:migrate
      - name: RSpec テスト実行
        run: bundle exec rspec

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Bundler & 依存関係インストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: git remote 確認 (デバッグ用)
        run: git remote -v
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          branch: main
